version: '3'
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:16
    working_dir: /usr/src/node-clean-code
    restart: always
    command: bash -c "npm install --production && npm install -D nodemon && npm run debug"
    volumes:
      - ./dist/:/usr/src/node-clean-code/dist/
      - ./package.json:/usr/src/node-clean-code/package.json
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo